use_frameworks!

platform :ios, '9.0'

target 'ScreenSizeManager_Example' do
  pod 'ScreenSizeManager', :path => '../'

  target 'ScreenSizeManager_Tests' do
    inherit! :search_paths

    
  end
end
